# Generated by Django 5.2.5 on 2025-08-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timezone', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BussinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField()),
                ('startTimeLocal', models.TimeField()),
                ('endTimeLocal', models.TimeField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapi.store')),
            ],
        ),
    ]
