# Generated by Django 5.2.5 on 2025-08-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=60),
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapi.store')),
            ],
        ),
    ]
