# Generated by Django 5.2.5 on 2025-08-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0002_alter_store_timezone_storestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete')], default='Running', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
