# Generated by Django 5.2.5 on 2025-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
